import productImage from '../assets/image/product.png';
import Steril from '../assets/image/vector.png';
import ogimage from '../assets/image/ogimage.png';
import tanif from '../assets/image/tanif.png';
import toper from '../assets/image/toper.png';
//ogimage
export const product = {
    products:[
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ',
            sm:[10,10],
            shert:12,
            hat:100,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ',
            sm:[10,10],
            shert:8,
            hat:100,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[10,10],
            shert:12,
            hat:5,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[10,10],
            shert:8,
            hat:5,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ',
            sm:[7.5,7.5],
            shert:12,
            hat:100,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ',
            sm:[7.5,7.5],
            shert:8,
            hat:100,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[7.5,7.5],
            shert:12,
            hat:10,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ (ինդիվիդուալ)',
            sm:[7.5,7.5],
            shert:8,
            hat:10,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ',
            sm:[5,5],
            shert:12,
            hat:100,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ոչ ստերիլ',
            sm:[5,5],
            shert:8,
            hat:100,
            vector:null,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[5,5],
            shert:12,
            hat:10,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[5,5],
            shert:8,
            hat:10,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ',
            sm:[16,14],
            shert:2,
            hat:10,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[16,14],
            shert:2,
            hat:10,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ',
            sm:[45,29],
            shert:2,
            hat:5,
            vector:Steril,
        },
        {
            img:productImage,
            name:'Բշժկական Անձեռոցիկ ստերիլ (ինդիվիդուալ)',
            sm:[45,29],
            shert:2,
            hat:5,
            vector:Steril,
        },
    ],
    partner:[
        {img:ogimage},
        {img:ogimage},
        {img:ogimage},
        {img:ogimage},
        {img:ogimage},
        {img:ogimage},
    ],
    bandage:[
        {
            img:productImage,
            name:'բժշկական ԲԻՆՏ ՍՏԵՐԻԼ',
            sm:[16,10],
            shert:2,
            hat:5,
            vector:Steril,
        },
        {
            img:productImage,
            name:'բժշկական ԲԻՆՏ ոչ ՍՏԵՐԻԼ Անձեռոցիկ ոչ ստերիլ',
            sm:[16,10],
            shert:8,
            hat:100,
            vector:null,
        },
    ],
    tanzif:[
        {
            img:tanif,
            name:'բժշկական թանզիֆ ոչ ՍՏԵՐԻԼ',
            sm:[90,3],
            shert:8,
            hat:100,
            vector:null,
        },
    ],
    toper:[
        {
            img:toper,
            name:'ԹՈՓԵՐ',
            sm:[90,100],
            shert:8,
            hat:100,
            vector:null,
        },
    ]
}